/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "primary": "#904d00",
        "primary-container": "#ff8c00",
        "primary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#ffb77d",
        "on-primary": "#ffffff",
        "on-primary-container": "#623200",
        "on-primary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#6e3900",
        "secondary": "#515f74",
        "secondary-container": "#d5e3fc",
        "secondary-fixed": "#d5e3fc",
        "secondary-fixed-dim": "#b9c7df",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#57657a",
        "on-secondary-fixed": "#0d1c2e",
        "on-secondary-fixed-variant": "#3a485b",
        "tertiary": "#00658f",
        "tertiary-container": "#00b5fc",
        "tertiary-fixed": "#c7e7ff",
        "tertiary-fixed-dim": "#85cfff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#004360",
        "on-tertiary-fixed": "#001e2e",
        "on-tertiary-fixed-variant": "#004c6c",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#564334",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "outline": "#897362",
        "outline-variant": "#ddc1ae",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        inter: ["Inter"],
        headline: ["Inter-Bold"],
        body: ["Inter-Regular"],
        label: ["Inter-Medium"],
      },
      borderRadius: {
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      boxShadow: {
        "kinetic": "0 8px 24px rgba(25, 28, 30, 0.06)",
        "premium": "0 12px 32px rgba(144, 77, 0, 0.1)",
      },

    },
  },
  plugins: [],
};
